version: '3.8'

services:

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    networks:
      - myNetwork

  web:
    container_name: web
    restart: unless-stopped
    build: ./
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - myNetwork

volumes:
  jpetstore-data:

networks:
  myNetwork:
    driver: bridge
    external: true
